version: '3'

services:
  db:
    image: postgres:12
    env_file:
      - ./pyazo_api/.env
    volumes:
    - db:/var/lib/postgresql/data

  api:
    build: .
    image: pyazo
    volumes:
      - public:/app/public
    ports:
      - 127.0.0.1:8000:8000
    env_file:
      - ./pyazo_api/.env

volumes:
  db:
  public: