FROM migrate/migrate

ENTRYPOINT ["/bin/sh", "-c", "migrate -path=/migrations/ -database postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST:5432/$POSTGRES_DB?sslmode=disable up"]

COPY migrations/ /migrations/
