version: '3'

services:
  db:
    image: postgres:12-alpine
    env_file:
      - .env
    volumes:
    - db:/var/lib/postgresql/data

  api:
    image: hub.theedgeofrage.com/pyazo/api
    volumes:
      - public:/app/public
    ports:
      - 127.0.0.1:8028:8000
    env_file:
      - .env

volumes:
  db:
  public:
