version: '3'

services:
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: pyazo
    volumes:
    - db:/var/lib/postgresql/data

  api:
    build: .
    volumes:
      - public:/app/public
    ports:
      - 127.0.0.1:8000:8000

volumes:
  db:
  public: