version: '3'

services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pyazo
    ports:
    - 3306:3306
    volumes:
    - db_data:/var/lib/mysql

volumes:
  db_data: