---
version: '3'
services:
  db:
    image: postgres:13-alpine
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data

  migrations:
    image: pyazo/migrations
    restart: 'no'
    env_file:
      - .env

  api:
    image: pyazo/api
    restart: unless-stopped
    volumes:
      - ${HOST_PUBLIC_MEDIA}:/app/media/public
      - private:/app/media/private
    ports:
      - ::1:8000:8000
    env_file:
      - .env

volumes:
  db:
  private:
