version: '3'

services:
  db:
    image: postgres:12
    env_file:
      - ./pyazo_api/.env
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
  public: