package auth

import (
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestHashAndVerify(t *testing.T) {
	hash, err := HashPassword("secret123")
	require.NoError(t, err)
	assert.True(t, strings.HasPrefix(hash, "$argon2id$v="))

	ok, err := VerifyPassword(hash, "secret123")
	require.NoError(t, err)
	assert.True(t, ok, "correct password should verify")

	ok, err = VerifyPassword(hash, "wrongpassword")
	require.NoError(t, err)
	assert.False(t, ok, "wrong password should not verify")
}

func TestVerifyPasslibHash(t *testing.T) {
	// Hash generated by Python passlib.hash.argon2
	// passlib.hash.argon2.hash("password123")
	// This verifies Go can read hashes created by the Python implementation
	hash := "$argon2id$v=19$m=65536,t=3,p=4$j/Feq1WKkdJ6by0lpNSacw$HSEoZwXkrGxtKPYZSmgCebf8SKBsmq6obj0hrqjjkqs"

	ok, err := VerifyPassword(hash, "password123")
	require.NoError(t, err)
	assert.True(t, ok, "failed to verify passlib-generated hash")
}

func TestHashUniqueness(t *testing.T) {
	h1, _ := HashPassword("same")
	h2, _ := HashPassword("same")
	assert.NotEqual(t, h1, h2, "two hashes of same password should differ (different salts)")
}

func TestCreateAndParseToken(t *testing.T) {
	token, err := CreateToken("alice", "test-secret")
	require.NoError(t, err)

	username, err := ParseToken(token, "test-secret")
	require.NoError(t, err)
	assert.Equal(t, "alice", username)
}

func TestParseTokenWrongSecret(t *testing.T) {
	token, _ := CreateToken("alice", "secret1")
	_, err := ParseToken(token, "secret2")
	assert.Error(t, err)
}

func TestParseTokenInvalid(t *testing.T) {
	_, err := ParseToken("garbage", "secret")
	assert.Error(t, err)
}
